### PR TITLE
Add methods to request a new access_token and refresh an existing one

### PR DESCRIPTION
**Pull request by addbrick**
I didn't find this in the gem so I quickly added it. Let me know if I just missed this, or any other suggestions.

### CODE REVIEW

**Comment by kyleboe** [comment]
I believe this is resolved by #30. Let me know if that resolves the issue and close the PR if it does. If not, we can discuss.

Either way, thanks for contributing! 😄

**Comment by addbrick** [comment]
@kyleboe @cwyn It looks like that should work, but when I tested it, I got an error about the header. Any ideas?
```
client = Zoom::Client::OAuth.new(auth_token: auth_token, auth_code: access_code, redirect_uri: redirect_uri, timeout: 15).auth
ArgumentError: header field value cannot include CR/LF
        from /Users/addisonbrickey/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/net/http/header.rb:23:in `block in initialize_http_header'
        from /Users/addisonbrickey/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/net/http/header.rb:16:in `each'
        from /Users/addisonbrickey/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/net/http/header.rb:16:in `initialize_http_header'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/httparty-0.13.7/lib/httparty/request.rb:176:in `setup_raw_request'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/httparty-0.13.7/lib/httparty/request.rb:114:in `perform'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/httparty-0.13.7/lib/httparty.rb:492:in `post'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/bundler/gems/zoom_rb-064f5c1e9d51/lib/zoom/actions/token.rb:9:in `access_tokens'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/bundler/gems/zoom_rb-064f5c1e9d51/lib/zoom/clients/oauth.rb:37:in `oauth'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/bundler/gems/zoom_rb-064f5c1e9d51/lib/zoom/clients/oauth.rb:27:in `auth'
        from (irb):11
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/addisonbrickey/.rvm/gems/ruby-2.4.6/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

Also I was wondering if we could not pass in the `auth_token` and instead generate from the api key and secret already in the config? I can make a PR for this change if wanted.

**Comment by cwyn** [comment]
Hi, sorry I can’t be of more help but all I can say at the moment is that it is working, there is an error with require_one_of when you try and get the refresh token but I don’t think it’s related to the above error your receiving. I think you may be able to check the base64 encoding for the token.

**Comment by addbrick** [comment]
No worries, this was just a quick pass at it so I need to spend more time
digging into the error. Good to know it is working for you, so most likely
it is something in my setup. Thanks!

**Comment by addbrick** [comment]
Update, I unfortunately am just getting back to this, will close this in favor of what has been merged.

**Comment by addbrick** [comment]
Figured out what the network error was caused by. There was a newline in my auth token when I base64 encoded it. Using `Base64.strict_encode64` will not insert newlines and fixes the error.

**Pull request closed without merging**
