### PR TITLE
Updated meeting to work properly

### PR DESCRIPTION
**Pull request by eclemens**
I updated meetings class. There were several methods that weren't working. Also simplified the access_token assignation using headers instead of query.

### CODE REVIEW

**Comment by kyleboe** [comment]
Hey there @eclemens! Thanks for your contribution to the gem! I haven't had a chance to look at it yet but will have time to review it after the first of the year. Thanks for your patience 😄

**Comment by shohey1226** [comment]
@kyleboe  Do you plan to merge this? Currently meeting_list is not working and would like to have them.

**Comment by kyleboe** [comment]
Ah shoot! So sorry! Been sleeping on my GH notifications and busy with other work things. I'm getting back on the stick now @shohey1226 & @eclemens

**Comment by shohey1226** [comment]
@kyleboe  Thanks for merging this!  (sorry for the late response)

**Pull request merged**
