### PR TITLE
KMP-3014: improve error generation

### PR DESCRIPTION
**Pull request by Tekkon**
It's hard to handle errors generated by the gem in the App which uses it because the errors are too common. There is only Zoom::AuthenticationError and Zoom::Error for any other cases.

This PR improves error generation. The error classes added for common http codes.
https://marketplace.zoom.us/docs/api-reference/error-definitions is used for reference.

### CODE REVIEW

**Review by kyleboe — APPROVED** [review]
Looks good! Thanks again for the contribution. I'll get this merged in and a new gem cut here shortly.

**Comment by tjefferson08** [comment]
Isn't this a breaking change? If I have `rescue Zoom::Error` in my codebase, raising these new, granular errors will no longer be caught (since they don't inherit from Zoom::Error)

(do I have that right?)

**Comment by kyleboe** [comment]
@tjefferson08 you're totally right. Apologies if this caused any disruption. I opened up #435 with a couple smoke tests to ensure we are descending from `Zoom::Error`. Thanks for catching this.

**Comment by tjefferson08** [comment]
Thanks for the quick response & repair! 🥇

**Comment by kyleboe** [comment]
@tjefferson08 to close the loop on this, the fix is included in [1.1.4](https://github.com/hintmedia/zoom_rb/releases/tag/v1.1.4)

**Pull request merged**
