### PR TITLE
Smata

### PR DESCRIPTION
**Pull request by viveki2it**
- Moved auth_token to the client class. We do not need to pass it every time.
- Added some required API's

### CODE REVIEW

**Review by kyleboe — CHANGES_REQUESTED** [review]
A couple of adjustments then this should be good to go.

Thanks for the contribution!

**Comment by kyleboe** [comment]
Also, it looks like there was a bit of overlap in this branch and another PR that was merged in. I merged master back into your branch.

**Comment by viveki2it** [comment]
@kyleboe Please review the latest changes and merge it to master. I will use it from the master branch. Thanks

**Review by kyleboe — APPROVED** [review]
LGTM 👍

**Pull request merged**
